### ISSUE TITLE
null icon on Quads

### ISSUE THREAD

**Issue by InfinityRaider** [InfinityRaider/InfinityLib#11]
http://pastebin.com/FgbGmgZY

**Comment by Eufranio** [comment]
Not fixed yet?

**Comment by InfinityRaider** [comment]
No

**Comment by Eufranio** [comment]
RIP

**Comment by InfinityRaider** [comment]
Problem is, I have not managed to reproduce this crash, and I have no idea what can be null there or why...

**Comment by InfinityRaider** [comment]
I think I fixed this, I'm going to close this for now, IF it occurs again, it'll be a different stacktracke, which should be more useful, so please report it again then.
