### ISSUE TITLE
Rendering crash

### ISSUE THREAD

**Issue by cleverpanda** [InfinityRaider/InfinityLib#14]
I'm not sure if this is your fault, but your code is erroring, and I've gotten this a few times. Generally happens close to a world start or not at all.

Log: http://pastebin.com/5DEPGm1P

**Comment by InfinityRaider** [comment]
Yes, that was my bad, but I already resolved this before anyone had reported it, thanks for reporting it anyway though.

**Comment by InfinityRaider** [comment]
(Was fixed in this commit: https://github.com/InfinityRaider/InfinityLib/commit/ad17193f586e0661250ebed30370064ceccd7517)
