### ISSUE TITLE
Seed Analyzer

### ISSUE THREAD

**Issue by jamesfhj** [InfinityRaider/InfinityLib#15]
So, I grabbed the newest version of Agricraft (2.0.0-0.4.0-a5) and Infinitylib (0.4.0). The cropsticks no longer crash my game, which is awesome. However, now the Seed Analyzer doesn't work. I can't put seeds in it at all. For clarification, I've only tried regular old Seeds that you get from breaking tall grass. I also can't seem to plant those seeds with the cropsticks either. I can place the cropsticks, but not with seeds. I've tried placing the cropsticks, then the seeds, as well as placing seeds then cropsticks.

Second issue, the book has no recipe on JEI. Not sure if you do that on your end, or if I should hit up the JEI folks for that one.

**Comment by InfinityRaider** [comment]
Ok, thanks for bringing this to our attention, but why are you reporting this on the InfinityLib tracker?

**Comment by jamesfhj** [comment]
Because I'm stupid, and forgot to switch to the Agricraft github. Apologies. I'll post this over there.
