### ISSUE TITLE
Problem with Agricraft - GUI of the seedAnalyzer won't open (InfinityLib 0.11.0)

### ISSUE THREAD

**Issue by MBelhardi** [InfinityRaider/InfinityLib#25]
Hello I found a problem with AgriCraft, which use this library. when I us the Version 0.11.0 of InfinityLib, then the GUI of the seedanalyzer won't open. If I use the prior Version 0.10.0 there isn't this problem.

**Comment by InfinityRaider** [comment]
Okay thanks for the report, this should be helpful

**Comment by winnetrie83** [comment]
I have the same issue. I downgraded also.

**Comment by InfinityRaider** [comment]
Closing since I am moving to 1.16 where this is no longer relevant.
