### ISSUE TITLE
Crash with JEI (not using Journeymap)

### ISSUE THREAD

**Issue by Geethebluesky** [InfinityRaider/InfinityLib#26]
I'm getting the same crash as everyone else in issue #20, except I don't use Journeymap. I do have Voxelmap and Optifine, though.

[Crash log](https://gist.github.com/Geethebluesky/96dc525a11a170384623e3013e8b2520)

I tried seeing what causes the crash and it seems to occur when a resource pack is loaded, with Optifine D3, Agricraft, the latest JEI (build 196 as of this comment) and Infinitylib. Simply searching for any item in the JEI interface causes this.

**Comment by InfinityRaider** [comment]
If this is the same crash as #20, do not create a new ticket for it...
