### ISSUE TITLE
Crash with Avatar Mod 2: Out of the Iceberg

### ISSUE THREAD

**Issue by FavouriteDragon** [InfinityRaider/InfinityLib#27]
https://github.com/AgriCraft/AgriCraft/issues/1205
Basically, it messes with an import.

**Comment by InfinityRaider** [comment]
Is the mod Open Source?

**Comment by FavouriteDragon** [comment]
Yep!
It's getting rewritten, but the branch we're currently using is FD/OldPackets.
https://github.com/ProjectKorra/AvatarMod/tree/FD/OldPackets

**Comment by FavouriteDragon** [comment]
This is what's crashing:
https://github.com/ProjectKorra/AvatarMod/blob/FD/OldPackets/src/main/java/com/crowsofwar/avatar/client/render/RenderArc.java

**Comment by InfinityRaider** [comment]
Strange, can it be that it is because InfinityLib ships joml as well?
https://github.com/InfinityRaider/InfinityLib/blob/c427fea603c0eee50b44c59759cd78fa3a4d14ee/build.gradle#L37-L39

https://github.com/ProjectKorra/AvatarMod/blob/FD/OldPackets/build.gradle#L44-L46

**Comment by InfinityRaider** [comment]
The stacktrace displays this:
java.lang.NoSuchMethodError: org.joml.Vector4d.mul(Lorg/joml/Matrix4d;)Lorg/joml/Vector4d;

I have no idea what that 'L' is doing there...

**Comment by FavouriteDragon** [comment]
Ok I'll try doing that!
Yeah I don't either 😂

**Comment by InfinityRaider** [comment]
Closing since I am moving to 1.16 where this is no longer relevant (I am no longer using joml).
