### ISSUE TITLE
Crash! ALREADY CONSTRUCTING VERTICALS when searching anything in JEI. InfinityLib causes this !

### ISSUE THREAD

**Issue by Speecker** [InfinityRaider/InfinityLib#32]
As the title says the current InfinityLib causes a ALREADY CONSTRUCTING VERTICALS Crash.
Confirmed that InfinityLib is causing this !
Please Do Fix This As This Is actually the only Lib Version available and Agricraft is the only Mod in my modpack depending on infinity lib.

**Comment by MusicMaestro123** [comment]
And here is a crash report to support it: [https://pastebin.com/7y5MP2c3](https://pastebin.com/7y5MP2c3)

**Comment by Speecker** [comment]
Still Requesting A Fix
Also Newer JEI Versions arent able to handle this issue

**Comment by aaronhowser1** [comment]
Another crash: https://pastebin.pl/view/35730c6a

**Comment by InfinityRaider** [comment]
Closing since I am moving to 1.16 where this is no longer relevant.
