### ISSUE TITLE
[Bug] 2.0.2 version tagged as 2.0.1

### ISSUE THREAD

**Issue by arBorghi** [InfinityRaider/InfinityLib#34]
It's a simple mistake but because of that i can't use the last version of 3D Maneuver Gear mod (it fixes important bugs).
![image](https://user-images.githubusercontent.com/63486777/111378741-02c06b00-8681-11eb-82f2-f6453b090143.png)

**Comment by InfinityRaider** [comment]
Huh, but it's not though: https://github.com/InfinityRaider/InfinityLib/blob/master/src/main/resources/META-INF/mods.toml#L8

**Comment by InfinityRaider** [comment]
Okay, I did git wrong before compiling.
I've pulled the build from CurseForge and uploaded a correct one.
Should be approved soon.
