### ISSUE TITLE
[Crash] Crash involving this mod and CodeChicken lib, refers to "tesselating liquid"

### ISSUE THREAD

**Issue by Corvus20** [InfinityRaider/InfinityLib#35]
Can't really make sense of anything else about it, here's the crash log.

[crash-2021-06-06_15.36.47-client.txt](https://github.com/InfinityRaider/InfinityLib/files/6604790/crash-2021-06-06_15.36.47-client.txt)

**Comment by InfinityRaider** [comment]
Optifine... Dont report issues with optifine
