### ISSUE TITLE
Crash with Agricraft

### ISSUE THREAD

**Issue by SanderWxD** [InfinityRaider/InfinityLib#38]
Updated to latest version of InfinityLib and now my modpack crashes upon starting it.

(No Optifine this time 😃)

[crash-2021-06-09_23.25.15-client.txt](https://github.com/InfinityRaider/InfinityLib/files/6626987/crash-2021-06-09_23.25.15-client.txt)

**Comment by InfinityRaider** [comment]
This is 1.12 though?
I have abandoned 1.12

**Comment by InfinityRaider** [comment]
Anyway, try updating agricraft to the latest for 1.12 as well, it seems you have an outdated version.
