### ISSUE TITLE
ATTEMPTED TO SEND AN UNREGISTERED MESSAGE

### ISSUE THREAD

**Issue by EmersonBiggons** [InfinityRaider/InfinityLib#43]
I have no idea why but it keeps kicking/crashing people game
[latest.log](https://github.com/InfinityRaider/InfinityLib/files/7272405/latest.log)

**Comment by InfinityRaider** [comment]
Fixed in AgriCraft: https://github.com/AgriCraft/AgriCraft/commit/95616bcb9769c39dc6a5cacc44b5f45d13bdd7e2
