### ISSUE TITLE
[1.18.2] Crash when placing a IntegratedTunnels World Energy Exporter (maybe more blocks) w/ InfinityLib installed.

### ISSUE THREAD

**Issue by Gbergz** [InfinityRaider/InfinityLib#46]
> Crash when placing a IntegratedTunnels World Energy Exporter (maybe more blocks) w/ InfinityLib installed.

### Versions:
Minecraft: 1.18.2
Forge: 40.1.47
InfinityLib: 2.1.1 | https://www.curseforge.com/minecraft/mc-mods/infinitylib/files/3818847

Crash-Report: https://gist.github.com/Gbergz/a87bf93f488f3511d96063a69de3162a

**Note:**
Not sure if this mod is causing this entirely, but reporting to make sure.
**-** Gbergz

**Comment by InfinityRaider** [comment]
I'll fix it, thanks for reporting

**Comment by Gbergz** [comment]
Thanks! Apprecieate it :)
Is this fix being released to CF?

**Comment by InfinityRaider** [comment]
Not yet, want have some other things to fix as well first.
