### ISSUE TITLE
[1.18.2] Infinitylib Crash - TextureAtlasSprite.m_118393_(double)

### ISSUE THREAD

**Issue by liquidblur** [InfinityRaider/InfinityLib#48]
I will preference this by stating theres a small chance its a compatibility issue, that may not be on infinitylib but another mod, but here is the crash log

https://hastepaste.com/view/w0QvrF

**Comment by InfinityRaider** [comment]
You have optifine, check if it still happens without it

**Comment by InfinityRaider** [comment]
I think I have managed to fix this crash either way.
