### ISSUE TITLE
InfinityLib crash 1.16.5 forge Tesselating liquid in world 

### ISSUE THREAD

**Issue by hugonoss** [InfinityRaider/InfinityLib#50]
I was playing with around 50 mods and flying around in creative mode when my game crashed. Looking at the crash log, I believe it was because of InfinityLib.

[crash-2022-07-08_23.26.37-client.txt](https://github.com/InfinityRaider/InfinityLib/files/9075151/crash-2022-07-08_23.26.37-client.txt)

**Comment by InfinityRaider** [comment]
You have optifine
